# Generated by Django 5.2.15 on 2026-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(choices=[('A', 'Class A CDL'), ('B', 'Class B CDL'), ('C', 'Class C CDL'), ('D', 'Class D Standard')], max_length=20)),
                ('license_expiry_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('safety_score', models.PositiveIntegerField(default=100, help_text='Driver Safety Score (0-100)')),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off Duty', 'Off Duty'), ('Suspended', 'Suspended')], default='Available', max_length=20)),
            ],
        ),
    ]
