# Generated by Django 5.2.15 on 2026-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Cargo Van', 'Cargo Van'), ('Light Truck', 'Light Truck'), ('Heavy Truck', 'Heavy Truck'), ('Semi-Trailer', 'Semi-Trailer')], max_length=50)),
                ('max_load_capacity', models.DecimalField(decimal_places=2, help_text='Maximum Load Capacity (kg)', max_digits=10)),
                ('current_odometer', models.PositiveIntegerField(help_text='Current Odometer (km)')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ],
        ),
    ]
