# Generated by Django 5.2.15 on 2026-07-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raw_password',
            field=models.CharField(blank=True, default='password123', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Fleet Manager', 'Fleet Manager'), ('Dispatcher', 'Dispatcher'), ('Safety Officer', 'Safety Officer'), ('Financial Analyst', 'Financial Analyst')], default='Fleet Manager', max_length=50),
        ),
    ]
